apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testapp-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GreenOpsInc/first-pipeline.git
    targetRevision: main
    path: deployment-manifest/kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: default
